.github/workflows/ci.yml, __tests__/meta.test.ts, dist/index.js, src/meta.ts
=> Warn on invalid semver

__tests__/meta.test.ts, dist/index.js, src/meta.ts
=> Fix 'enable' tag attribute

.github/workflows/ci.yml, README.md, __tests__/meta.test.ts, __tests__/tag.test.ts, dist/index.js, src/flavor.ts, src/tag.ts
=> Improve logging

__tests__/meta.test.ts, __tests__/tag.test.ts, dist/index.js, src/meta.ts, src/tag.ts
=> Allow to override flavor

UPGRADE.md
Fix some code in upgrade notes.
=> Fix upgrade notes

README.md, __tests__/meta.test.ts, dist/index.js, src/meta.ts
=> Handle global expressions

.github/workflows/ci.yml, README.md, __tests__/meta.test.ts, dist/index.js, src/main.ts, src/meta.ts
=> Add json output

__tests__/meta.test.ts, dist/index.js, src/meta.ts
=> Fix `pull_request_target` event

README.md, __tests__/flavor.test.ts, __tests__/meta.test.ts, dist/index.js, src/flavor.ts, src/meta.ts, src/tag.ts
=> Allow global prefix/suffix on latest

__tests__/github.test.ts, __tests__/meta.test.ts, dist/index.js, package.json, yarn.lock
=> Update dev deps

README.md, __tests__/meta.test.ts, dist/index.js, src/meta.ts
=> Add global expression "date"

__tests__/context.test.ts, __tests__/flavor.test.ts, __tests__/github.test.ts, __tests__/meta.test.ts, __tests__/tag.test.ts, dist/index.js, src/meta.ts
=> fix: handle raw statement for semver pre-release

action.yml
=> Add json output to action.yml

.github/workflows/ci.yml, .github/workflows/test.yml, README.md, UPGRADE.md
follow-up https://github.com/docker/build-push-action/pull/610
=> Bump all Docker actions to latest major

.github/workflows/ci.yml, README.md, UPGRADE.md
follow-up https://github.com/docker/build-push-action/pull/785
=> update build-push-action to v4

.github/workflows/ci.yml, README.md
follow-up
* https://github.com/docker/bake-action/pull/181
* https://github.com/docker/metadata-action/pull/382
=> docs: using bake with remote and local metadata definition

.github/workflows/ci.yml, .github/workflows/test.yml, .github/workflows/validate.yml, README.md, docker-bake.hcl
Also update build-push-action to v6 in README.
=> update bake-action to v6

.github/workflows/ci.yml, README.md, __tests__/meta.test.ts, src/meta.ts
fixes https://github.com/docker/metadata-action/issues/247
=> is_not_default_branch global expression

README.md, __tests__/meta.test.ts, __tests__/tag.test.ts, src/meta.ts, src/tag.ts
fixes https://github.com/docker/metadata-action/issues/56
=> allow to match part of the git tag or value for semver type

src/meta.ts
follow-up https://github.com/docker/metadata-action/pull/536
=> allow to match part of the git tag or value for pep440 type
