docker/metadata-action

- README.md
- __tests__/meta.test.ts
- action.yml
- dist/index.js
- src/meta.ts
> Handle tag-match-latest on Git tag event

- README.md
- __tests__/meta.test.ts
- dist/index.js
- package.json
- src/context.ts
- src/main.ts
- src/meta.ts
Closes #10 
Closes #6 
cc. @fastlorenzo
> Handle semver tags

- dist/index.js
- src/main.ts
This PR fixes the Action's `labels` output to use the correct separator.
> Use sepLabels when joining labels for output

- .github/workflows/ci.yml
- README.md
- __tests__/meta.test.ts
- action.yml
- dist/index.js
- src/context.ts
- src/meta.ts
> Allow to disable latest tag

- README.md
> Major version zero doc

- .github/workflows/test.yml
- README.md
- UPGRADE.md
> v3 upgrade notes

- README.md
- __tests__/meta.test.ts
- __tests__/tag.test.ts
- dist/index.js
- src/meta.ts
- src/tag.ts
> Add format attribute for type=sha

- README.md
- __tests__/meta.test.ts
- dist/index.js
- src/meta.ts
> Only return edge if branch matches

- README.md
See Issue #116.
README modified to make it clear that this action extracts metadata from Git to tag Docker images, rather than getting metadata from the docker registry.
> Update README (Issue #116)

- README.md
This PR adds a pep440 anchor to the list of types and updates the tags example to match the order the types are introduced.
> docs: add README pep440 anchor to list of types

- .github/workflows/ci.yml
- __tests__/meta.test.ts
- dist/index.js
- src/context.ts
> Preserve quotes inside unquoted field

- README.md
Hey! I had the same problem as described in https://github.com/docker/metadata-action/issues/147 and felt it had a place in the readme to save the next person around some time.
Does it make sense to you, and do you think the note is placed at the right place?
> docs: add example for latest tag with dynamic condition

- README.md
The current approach has some flaws. For example, branch `my-main` could be detected as default as it ends with `main`.
> Fine tune default branch example

- README.md
- __tests__/context.test.ts
- dist/index.js
- src/context.ts
> handle comments for multi-line inputs

- README.md
- UPGRADE.md
> readme: set metadata-action to v4

- .github/workflows/ci.yml
- test/json.Dockerfile
The step in the `json` job is no longer necessary since it is already done by the `output-env` job.
> ci: update json job

- README.md
> Update Bake file-reference URI

- .github/workflows/ci.yml
- README.md
- __tests__/meta.test.ts
- src/meta.ts
fixes #453 
Also adds `DOCKER_METADATA_SHORT_SHA_LENGTH` env var to customize short commit SHA length.
cc @rumpl @dvdksn
> increase short commit hash length to 12 for uniqueness

- README.md
- __tests__/context.test.ts
- __tests__/meta.test.ts
follow-up https://github.com/docker/metadata-action/pull/471#issuecomment-2484265272
@trim2 Fyi, I see in response schema that `commit.committer` for `/repos/{owner}/{repo}/commits/{ref}`: https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit
Can be null:
```json
"committer": {
"anyOf": [
{
"type": "null"
},
{
"title": "Git User",
"description": "Metaproperties for Git author/committer information.",
"type": "object",
"properties": {
"name": {
"type": "string",
"examples": [
"\"Chris Wanstrath\""
]
},
"email": {
"type": "string",
"examples": [
"\"chris@ozmm.org\""
]
},
"date": {
"type": "string",
"examples": [
"\"2007-10-29T02:42:39.000-07:00\""
]
}
}
}
]
},
```
If that happens it would just return the current date. I think that's fine but we could improve …
> commit_date: code cleanup and readme updates

- __mocks__/@actions/github.ts
- src/context.ts
> commiter_date: fix github api request fallback

- README.md
- __tests__/meta.test.ts
- src/meta.ts
fixes #479 
@rumpl @dgageot @dvdksn This breaks some workflows per #479 so let's revert to the previous default (`7`) but keep the env var to increase if necessary. We could set defaults back to `12` in next v6 major.
> back to commit sha length of 7

- .github/workflows/ci.yml
- README.md
- src/main.ts
Fixes #490. Introduces the ~`output-env` input~ `DOCKER_METADATA_SET_OUTPUT_ENV` environmental variable to the action which allows users to stop the action from creating the `DOCKER_METADATA_OUTPUT_*` environment variables.
> Support disabling `DOCKER_METADATA_OUTPUT_*` environment variables
